wttech/gradle-aem-plugin

build.gradle, src/main/kotlin/com/cognifide/gradle/aem/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/AemException.kt, src/main/kotlin/com/cognifide/gradle/aem/AemInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/AemPlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/PackageException.kt, src/main/kotlin/com/cognifide/gradle/aem/vlt/VltException.kt
=> Instance validation

src/main/kotlin/com/cognifide/gradle/aem/vlt/VltApp.kt
Changed order of args in checkout process
=> #20 Fixed order of arguments in Checkout 

build.gradle, src/main/kotlin/com/cognifide/gradle/aem/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/AemPlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/Patterns.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/PropertyParser.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/ComposeTask.kt, src/main/resources/META-INF/vault/filter.xml
=> Deploy rule task

build.gradle, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalHandle.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/PropertyParser.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/FileOperations.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/FileResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/HttpFileDownloader.kt, src/main/resources/com/cognifide/gradle/aem/META-INF/vault/filter.xml, src/main/resources/com/cognifide/gradle/aem/META-INF/vault/properties.xml, src/main/resources/com/cognifide/gradle/aem/local-instance/start.bat, src/main/resources/com/cognifide/gradle/aem/local-instance/start.sh
(to avoid collision with quickstart felix vars which are using same syntax, but shouldn't be expanded)
=> #55 | New syntax for expandable vars

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/FileException.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/FileResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/HttpFileDownloader.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/SftpFileDownloader.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/SmbFileDownloader.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/UrlFileDownloader.kt, src/main/kotlin/com/cognifide/gradle/aem/vlt/VltCleaner.kt, src/test/kotlin/com/cognifide/gradle/aem/vlt/NopLogger.kt, src/test/kotlin/com/cognifide/gradle/aem/vlt/VltCleanerTest.kt, src/test/resources/com/cognifide/gradle/aem/vlt/cleanupDotContent/defaultClosing-expected.xml, src/test/resources/com/cognifide/gradle/aem/vlt/cleanupDotContent/defaultClosing.xml, src/test/resources/com/cognifide/gradle/aem/vlt/cleanupDotContent/selfClosing-expected.xml, src/test/resources/com/cognifide/gradle/aem/vlt/cleanupDotContent/selfClosing.xml, src/test/resources/com/cognifide/gradle/aem/vlt/filterLines.xml
TDD, firstly cover the case using unit test, then apply a fix for bug.
When skipped property is last and after it there are self-closing characters "/>", plugin leaves ">" instead of "/>" and that should be fixed.
=> VLT clean edge case 

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/com/cognifide/gradle/aem/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/vlt/VltCleaner.kt, src/main/kotlin/com/cognifide/gradle/aem/vlt/VltContentProperty.kt
=> VLT clean exclude paths

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/base/api/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/BundleState.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/CreateTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/DestroyTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/DownTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceActions.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstancePlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceState.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceSync.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalHandle.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/ReloadTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/UpTask.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/deploy/SyncTask.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/common/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/core/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/build.gradle
Works both with remote and local instances ;)
=> Instance reload task 

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/build.gradle
Helped on edge case, should not be disabled by default
=> Satisfy install retry default

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceType.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceUrl.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/RemoteInstance.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/build.gradle
=> Instances DSL

build.gradle, src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceType.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceUrl.kt
=> HTTP port optional / defaults

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/api/AemDefaultTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/CreateTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/DestroyTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/SatisfyTask.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/file/resolver/FileResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/deploy/DeleteTask.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/deploy/PurgeTask.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/deploy/UninstallTask.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/settings.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/build.gradle
=> Satisfy by command line

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/api/AemNotifier.kt, src/main/kotlin/com/cognifide/gradle/aem/bundle/BundlePlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/AwaitTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/action/AwaitAction.kt, src/test/kotlin/com/cognifide/gradle/aem/test/DebugTaskTest.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/settings.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json
=> Final fixes (4.0.0)

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/pkg/ComposeTask.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/settings.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/build.gradle
fixed - `sh gradlew :content:build` / assembled content package only
=> Release 4.0.7

build.gradle, src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt, src/main/kotlin/com/cognifide/gradle/aem/api/AemNotifier.kt, src/main/kotlin/com/cognifide/gradle/aem/api/AemPlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/notifier/DorkboxNotifier.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/notifier/JcGayNotifier.kt, src/main/kotlin/com/cognifide/gradle/aem/internal/notifier/Notifier.kt
Continuation of #198 (lack of permission to write to Maciej's repo)
=> Native OS notification (continued)

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/base/vlt/RcpTask.kt, src/main/kotlin/com/cognifide/gradle/aem/base/vlt/VltRcpSummary.kt, src/main/kotlin/com/cognifide/gradle/aem/base/vlt/VltRunner.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/settings.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/build.gradle
=> RCP paths file

src/main/kotlin/com/cognifide/gradle/aem/instance/satisfy/PackageResolution.kt
@M-Paluchowski please verify if it is fixing your case
=> OSGi auto wrap jar fix

README.md, build.gradle, src/main/kotlin/com/cognifide/gradle/aem/instance/satisfy/PackageResolution.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/settings.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/build.gradle, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/build.gradle
The wildcard for *.cnd files was missed.
=> Osgi autowrap fix

README.md, build.gradle.kts, src/main/kotlin/com/cognifide/gradle/aem/common/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/FileOperations.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/Create.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json
unpacking previously created backup was corrupted sometimes. zip4j does the good job. zeroturnaround & gradle zip tree cannot be used.
=> Backup fix

README.md, build.gradle.kts, src/main/kotlin/com/cognifide/gradle/aem/bundle/BundleJar.kt, src/main/kotlin/com/cognifide/gradle/aem/common/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/AemPlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/common/TaskFacade.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/resolver/Resolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/resolver/ResolverOptions.kt, src/main/kotlin/com/cognifide/gradle/aem/config/Config.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstanceOptions.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/Backup.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/Create.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/Instance.kt, src/test/kotlin/com/cognifide/gradle/aem/test/DebugTaskTest.kt, src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/buildSrc/build.gradle.kts, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json
implemented #312 , #313 , #308
=> Release 6.0.1

src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckGroup.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/DefaultCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupType.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/Source.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Node.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/TaskSequence.kt, src/main/kotlin/com/cognifide/gradle/aem/environment/hosts/HostsUnix.kt, src/main/kotlin/com/cognifide/gradle/aem/environment/hosts/HostsWindows.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceBackup.kt, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json
* new instance source mode - backup only;
* file stat only for protocols supporting it when resolving backup source
=> Backup hardenings

src/main/kotlin/com/cognifide/gradle/aem/common/instance/AbstractInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/PackageTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/satisfy/InstanceSatisfy.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageActivate.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageDelete.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageDeploy.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageInstall.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackagePurge.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageUninstall.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageUpload.kt
=> Unavailable instances reporting

README.md, gradle/wrapper/gradle-wrapper.properties
Gradle 5.6.1 is available.
This is sent by @gradleupdate. See https://gradleupdate.appspot.com/Cognifide/gradle-aem-plugin/status for more.
=> Gradle 5.6.1

README.md, src/main/kotlin/com/cognifide/gradle/aem/environment/docker/domain/HttpdContainer.kt, src/main/kotlin/com/cognifide/gradle/aem/environment/docker/domain/Stack.kt
https://stackoverflow.com/a/51411304 
GAP will report nice hint only on Windows:
=> Docker for Windows / shared drive hints on error

README.md, src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/build/PropertyParser.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/InstallResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Node.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Repository.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/workflow/WorkflowManager.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/satisfy/InstanceSatisfy.kt, src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json, src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json
=> Workflow restore retry

src/main/kotlin/com/cognifide/gradle/aem/common/file/transfer/FileDownloader.kt, src/main/kotlin/com/cognifide/gradle/aem/common/utils/Formats.kt
Pull request for enhancement: https://github.com/Cognifide/gradle-aem-plugin/issues/367
=> Remaining time download enhancement

src/main/kotlin/com/cognifide/gradle/aem/common/build/Parallel.kt, src/main/kotlin/com/cognifide/gradle/aem/common/build/ProgressIndicator.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/resolver/FileGroup.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/resolver/Resolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/utils/Formats.kt
=> Resolver parallel fix / Gradle 6 compatibility

src/main/kotlin/com/cognifide/gradle/aem/AemTaskFacade.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageCompose.kt
=> Dependency notation type

README.MD, src/functionalTest/kotlin/com/cognifide/gradle/aem/bundle/BundlePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildResult.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckProgress.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckRunner.kt
=> Concurrent modification fix

src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/vault/VaultDefinition.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceBackup.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageCompose.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/compose/BundleInstalled.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/compose/BundleInstalledBuilt.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/compose/BundleInstalledResolved.kt
removed now redundant `fromProject*()` methods, recovered support for run modes customization for installed bundles
=> Package composer redesign (final improvements)

src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/InstancePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/LocalInstancePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildResult.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceBackup.kt
+ fixes to instanceBackup task
=> + tests for local instance setup and backup

src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/ComponentsCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/EventsCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/utils/Utils.kt, src/test/kotlin/com/cognifide/gradle/aem/common/utils/UtilsTest.kt
=> Shorten class in check runner

build.gradle.kts, src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/local/LocalInstancePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildResult.kt, src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/FileOperations.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/ZipException.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/ZipFile.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckGroup.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckProgress.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckRunner.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageDefinition.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageFile.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageValidator.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceBackup.kt
impl of #415 
removed zeroturnaround zip util
=> Zip clean up

src/functionalTest/kotlin/com/cognifide/gradle/aem/bundle/BundlePluginTest.kt
=> Bundle m2 publish test

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/local/LocalInstancePluginTest.kt, src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/action/AwaitUpAction.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckFactory.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckRunner.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/ComponentsCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/EventsCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/pkg/Package.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/pkg/PackageManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/vault/VaultDefinition.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/InstancePlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceAwait.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceStatus.kt
PoC, work in progress; impl of #644
=> Instance status task

src/main/kotlin/com/cognifide/gradle/aem/bundle/tasks/BundleInstall.kt, src/main/kotlin/com/cognifide/gradle/aem/bundle/tasks/BundleUninstall.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/SyncFileTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceAwait.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceProvision.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceSatisfy.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceUp.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageActivate.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageDelete.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageDeploy.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageInstall.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackagePurge.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageUninstall.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageUpload.kt
=> Sync file task improvements

build.gradle.kts, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupSource.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/InstallResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/status/Status.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/InstanceLogInfo.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/Log.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/LogInfo.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/LogParser.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/LogTailer.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/NoLogInfo.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/Tailer.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/io/ConsolePrinter.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/InstanceTask.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/LocalInstanceTask.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/SyncFileTask.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceStatus.kt, src/test/kotlin/com/cognifide/gradle/aem/common/instance/tail/InstanceTailTest.kt
=> Instance status improvements

build.gradle.kts, src/main/kotlin/com/cognifide/gradle/aem/AemVersion.kt, src/main/kotlin/com/cognifide/gradle/aem/common/file/ZipFile.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/Script.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/workflow/Workflow.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/Tailer.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceAwait.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceCreate.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceDown.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceStatus.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceUp.kt
I am rather lazy... and already too many times helped people in case of proving people that they are using wrong Java version. Since now, GAP will tell that to build users / AEM devs immediately and automatically.
=> Java compatibility prerequisite checking

README.MD, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageCompose.kt
=> Package compose - Gradle 6.3 fix

docs/instance-plugin.md, docs/package-plugin.md, src/main/kotlin/com/cognifide/gradle/aem/AemVersion.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/workflow/Workflow.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/workflow/WorkflowManager.kt
=> Workflow toggle hardened

src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Provisioner.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/satisfy/Satisfier.kt
=> Toggling satisfy and provision

README.MD, src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildResult.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/vault/VaultDefinition.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceStatus.kt
=> Package manifest tests

src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/OpenMode.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/Source.kt
=> Local instance autoopen

src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/action/AwaitUpAction.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/BundlesCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckFactory.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckGroup.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckProgress.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckRunner.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/ComponentsCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/DefaultCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/EventsCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/HelpCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/HelpException.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/osgi/Bundle.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/osgi/OsgiException.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/osgi/OsgiFramework.kt
=> Await up helper

build.gradle.kts, gradle.properties, src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/asset/AssetManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/cli/CliApp.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/utils/WebBrowser.kt
=> CLI apps concurrency fix

gradle.properties, src/main/kotlin/com/cognifide/gradle/aem/common/instance/StatusReporter.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/pkg/Package.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/pkg/PackageManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Node.kt, src/main/kotlin/com/cognifide/gradle/aem/common/tasks/SyncFileTask.kt, src/main/kotlin/com/cognifide/gradle/aem/common/utils/Checksum.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageDeploy.kt
impl of #702 
this feature does not deploy again package on instance if it is not changed (checksum based comparison of local package with checksum saved on instance)
=> Package deploy avoidance

README.MD, docs/launcher.md, gradle.properties, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/Launcher.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/LauncherException.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/StatusReporter.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceTail.kt
=> Launcher with saving properties

README.MD, docs/common-plugin.md, docs/instance-plugin.md, docs/local-instance-plugin.md, src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/local/LocalInstancePluginTest.kt, src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/action/ReloadAction.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/DefaultCheck.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/utils/ProcessKiller.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstancePlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceKill.kt
=> Thread safety fixes + instance kill task

launcher/build.gradle.kts, src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildResult.kt, src/main/kotlin/com/cognifide/gradle/aem/common/pkg/vault/VaultDefinition.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceBackup.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageCompose.kt
impl of #733 
+ minor UX improvements
=> Improvements

gradle.properties, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Provisioner.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Step.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/step/ConfigureCryptoStep.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/step/DeployPackageStep.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/pkg/PackageManager.kt
=> Package response dumping and provision await up before

src/asset/localInstance/defaults/service/start.sh, src/asset/localInstance/defaults/service/status.sh, src/asset/localInstance/defaults/service/stop.sh, src/asset/localInstance/service/start.sh, src/asset/localInstance/service/status.sh, src/asset/localInstance/service/stop.sh, src/asset/localInstance/service/systemd.conf, src/asset/localInstance/service/sysvinit.sh, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/ServiceComposer.kt
=> Common service 

src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceUp.kt
=> Up ensured

src/asset/oakrun/admin-reset.groovy.peb, src/main/kotlin/com/cognifide/gradle/aem/common/cli/CliApp.kt, src/main/kotlin/com/cognifide/gradle/aem/common/cli/JarApp.kt, src/main/kotlin/com/cognifide/gradle/aem/common/cli/JarException.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/oak/OakRun.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/oak/OakRunException.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/oak/OakRunScript.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceUp.kt
=> Local instance password resetter

src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceFactory.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckProgress.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckRunner.kt
=> Instance factory extracted / reset password enabled on higher envs by

docs/launcher.md, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/BuildScaffolder.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/step/DeployPackageStep.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/pkg/PackageManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/mvn/ModuleResolver.kt
=> Deploy avoidance fix

gradle.properties, src/main/kotlin/com/cognifide/gradle/aem/common/mvn/DependencyGraph.kt, src/main/kotlin/com/cognifide/gradle/aem/common/mvn/ModuleResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/mvn/MvnBuild.kt
=> Maven hybrid build with poms in the middle

launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/BuildScaffolder.kt
Also declare gradle-common-plugin's version explicitly.
=> Change dependencies' versions.

launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/BuildScaffolder.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/ForkScaffolder.kt
Also added a field for specifying the URI of the core components package
=> Add functionality of adding the service pack to the props

src/main/kotlin/com/cognifide/gradle/aem/common/pkg/vault/FilterFile.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageSync.kt
thx @mmajchrzak for reporting this.
=> Maven build / filter sync dedicated fix

src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/Log.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/LogParser.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/LogTailer.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/Tailer.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/io/UrlSource.kt, src/test/kotlin/com/cognifide/gradle/aem/common/instance/tail/InstanceTailTest.kt
#839 ->use `instance.tail.datePattern` to set custom date pattern from log file
e.g.` instance.tail.datePattern=yyyy-MM-dd HH:mm:ss.SSS`
=>  #839 added "instance.tail.datePattern" property

src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceDeploy.kt
=> multiple files deploy

gradle.properties, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/EnvCloudScaffolder.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/EnvOnPremScaffolder.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/EnvScaffolder.kt, src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/InstancePluginTest.kt, src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Auth.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceFactory.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceHttpClient.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/CheckProgress.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/JavaAgentResolver.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Condition.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Provisioner.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/crx/Crx.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/ReplicationAgent.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Repository.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/status/Status.kt, src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceTail.kt, src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageSync.kt
Jacoco, OpenTelemetry and NewRelic
implementation for #903 
also changed `var`s to Gradle provider API properties for easier chaining and better laziness
=> Jvm agents auto-provisioning

src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/JavaAgentResolver.kt, src/test/kotlin/com/cognifide/gradle/aem/common/CommonPluginTest.kt
=> broken imports, unneccesary broken lines

src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt, src/main/kotlin/com/cognifide/gradle/aem/bundle/BundlePlugin.kt, src/main/kotlin/com/cognifide/gradle/aem/bundle/tasks/BundleJar.kt
=> Convention feature removal

launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/EnvCloudScaffolder.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/EnvOnPremScaffolder.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/EnvScaffolder.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/ForkScaffolder.kt
Add a check for environment type and enforce publish and local urls if
type is set to 'local'
=> #918 Force localhost urls in launcher

docs/launcher.md, launcher/src/functionalTest/kotlin/com/cognifide/gradle/aem/launcher/LauncherTest.kt, launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/Launcher.kt
=> feat(launcher): allow passing arguments to wrapper task

src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt, src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/JavaAgentResolver.kt
=> Java agent download dir fix
