wttech/gradle-aem-plugin

src/main/kotlin/com/cognifide/gradle/aem/vlt/VltApp.kt
src/main/kotlin/com/cognifide/gradle/aem/vlt/VltCleaner.kt

`gradlew :example.content:aemSync`
ends with:
```
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
```
or
```
Checking out content from AEM
could not find jcr_root along the ancestors of C:\Users\krystian.panek\Projects\gradle-aem-example
Unexpected checkout[--force, http://localhost:4502, /, C:\Users\krystian.panek\Projects\gradle-aem-example\content\src\main\content] while processing . Type --help for more information.
Cleaning checked out JCR content
:example.content:aemSync (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.171 secs.
```

Fixing aemSync for subprojects

---

src/main/kotlin/com/cognifide/gradle/aem/AemInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/deploy/SyncTask.kt
src/main/kotlin/com/cognifide/gradle/aem/vlt/CheckoutTask.kt
src/main/kotlin/com/cognifide/gradle/aem/vlt/CleanTask.kt
src/main/kotlin/com/cognifide/gradle/aem/vlt/SyncTask.kt
src/main/kotlin/com/cognifide/gradle/aem/vlt/VltCommand.kt
src/main/kotlin/com/cognifide/gradle/aem/vlt/VltTask.kt

Needed to cover case:
```
aem {
config {
instance("http://localhost:4503", "admin", "admin", "local-publish")
}
}
```
then `gradle :content:demo:aemSync -i` ends with `List is empty` but checking out from publish should work anyway.

Default instance filter

---

src/main/kotlin/com/cognifide/gradle/aem/AemConfig.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/PrepareTask.kt

Fix for deprecation / warning introduced in Gradle API 4.3:
```
problem was found with the configuration of task ':common:aemPrepare'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
- Directory 'my-project\common\src\main\content\META-INF\vault' specified for property '$2' does not exist.
```

Optional input dirs / Gradle API alignment

---

README.md
build.gradle
src/main/kotlin/com/cognifide/gradle/aem/base/api/AemConfig.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/PackagePlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/jar/UpdateManifestTask.kt
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/common/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/core/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/debug/build.gradle

Also removed warning about supported OSGI related plugins.
Now will be supported all 'osgi', 'org.dm.bundle' and 'biz.aQute.bnd.builder' :>

Fix for 'No SCR metadata' in unit tests 

---

README.md
build.gradle
src/main/kotlin/com/cognifide/gradle/aem/base/api/AemConfig.kt
src/main/kotlin/com/cognifide/gradle/aem/base/vlt/VltCommand.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/CreateTask.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/Instance.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceSync.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceUrl.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/RemoteInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/internal/LineSeparator.kt
src/main/kotlin/com/cognifide/gradle/aem/internal/PropertyParser.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/ComposeTask.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/deploy/SyncTask.kt
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/common/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/debug/build.gradle

Also implemented:
* line separator by name / abbreviation
* default deploy instance name configurable (instead of hardcoded '*-local'), #64 
* instance url containing user and password, #107

Configuring behavior related properties via cmd line

---

README.md
build.gradle
src/main/kotlin/com/cognifide/gradle/aem/bundle/BundleCollector.kt
src/main/kotlin/com/cognifide/gradle/aem/bundle/BundleTask.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceActions.kt
src/main/kotlin/com/cognifide/gradle/aem/internal/ProgressLogger.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/ComposeTask.kt
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/debug/build.gradle

since 3.0.0-3.0.5, bundles being compiled could not be a part of CRX package, because Gradle input cache was badly registered in that case.
this PR will fix that and return previous good working behavior

Java incremental hotfix

---

src/main/kotlin/com/cognifide/gradle/aem/instance/Instance.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceType.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/LocalHandle.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/RemoteInstance.kt

* implemented #139 ; instance name will be just `typeName` as is (there will be need to rename directories `local-author` to `author` and `local-publish` to `publish`)
* added possibility to define multiple types of instance for each env, e.g
```
aem {
config {
remoteInstance('http://192.168.0.1', 'admin', 'admin', 'author1', 'int')
remoteInstance('http://192.168.0.2', 'admin', 'admin', 'author2', 'int')
remoteInstance('http://192.168.0.3', 'admin', 'admin', 'publish1', 'int')
remoteInstance('http://192.168.0.4', 'admin', 'admin', 'publish2', 'int')
}
}
```

Local instance dir name + multiple types per env

---

README.md
src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/InstanceSync.kt

* 3.0.9
Some environments does have SSL but no valid certificate. We'd like to deploy packaged also to those environments. I've added a flag `trustAllCertificates` which is by default set to `false`.
If switched to `true` connections also to untrusted (e.g. self-signed) SSL certificates will be allowed.

Allow ignoring ssl certificate while connecting to remote instance

---

README.md
build.gradle
src/main/kotlin/com/cognifide/gradle/aem/api/AemConfig.kt
src/main/kotlin/com/cognifide/gradle/aem/bundle/BundlePlugin.kt
src/test/resources/com/cognifide/gradle/aem/test/compose/assembly/gradle/buildscript.gradle
src/test/resources/com/cognifide/gradle/aem/test/compose/bundle-and-content/settings.gradle
src/test/resources/com/cognifide/gradle/aem/test/debug/additional/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json
src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/build.gradle
src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json

implementation of #214 ; bnd tool is already doing that as mentioned in issue, but... that root cause of reporting it was just a warning. this improvement is rather demonstrating how to handle warnings and make them build-breakable.

Bundle BND instructions via build script

---

src/main/kotlin/com/cognifide/gradle/aem/environment/Environment.kt
src/main/kotlin/com/cognifide/gradle/aem/environment/hosts/Host.kt
src/main/kotlin/com/cognifide/gradle/aem/environment/hosts/HostOptions.kt
src/main/kotlin/com/cognifide/gradle/aem/environment/tasks/EnvironmentHosts.kt

Motivation of this to be able to easy reuse host names defined in one place
also in custom tasks scripting:
https://github.com/Cognifide/gradle-aem-multi/issues/67
https://github.com/Cognifide/gradle-aem-multi/issues/68
to be able to write: `aem.environment.hosts.live.httpUrl` instead of hardcoding same domain in multiple places
or `aem.environment.hosts.author.httpUrl` etc

Environment hosts conventions

---

README.md
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/InstallResolver.kt
src/test/kotlin/com/cognifide/gradle/aem/test/DebugTest.kt
src/test/resources/com/cognifide/gradle/aem/test/debug/additional/debug.json
src/test/resources/com/cognifide/gradle/aem/test/debug/minimal/debug.json

impl of #431 
usage
instead of 
```kotlin
aem {
tasks {
instanceSatisfy {
packages {
download("http://my-company.com/aem/packages/my-package.zip")
}
}
}
}
```
will be possible:
```kotlin
aem {
localInstance {
install {
files {
download("http://my-company.com/aem/packages/my-package.zip")
}
}
}
}
```

Local instance pre-install dir

---

README.MD
build.gradle.kts
src/main/kotlin/com/cognifide/gradle/aem/instance/rcp/InstanceRcp.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/rcp/RcpClient.kt

updated vault-cli because the previous one seems that it is not working on AEM 6.4/6.5 in all cases.
https://www.apache.org/dist/jackrabbit/filevault/3.4.0/RELEASE-NOTES.txt
> Bug fixes:
* [JCRVLT-323] - Unable to perform sync due to wrong default workspace handling

RCP regression fixes

---

src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Node.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Repository.kt

node uploads is intelligent. when path is located under /content/dam then separate / dedicated DAM endpoint is used (which also is processing metadata and renditions) instead of default Sling one
```kotlin
aem {
tasks {
register("saveFile") {
doLast {
authorInstance.sync {
val source = repository.node("/content/dam/we-retail/en/features/cart.png")
val image = source.download()
logger.lifecycle("Downloaded image: $image")
val target = source.parent.child("${source.baseName}2.${source.extension}")
target.upload(image)
logger.lifecycle("Uploaded image to: $target")
}
}
}
}
}
```

Repository node upload and download files

---

build.gradle.kts
gradle.properties
src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/compose/BundleInstalledResolved.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/compose/PackageNestedResolved.kt

```kotlin
aem {
tasks {
packageCompose {
installBundle("com.neva.felix:search-webconsole-plugin:1.3.0")
installBundle("https://dl.bintray.com/neva-dev/maven-public/com/neva/felix/search-webconsole-plugin/1.3.0/:search-webconsole-plugin-1.3.0.jar") // new one! - alternatively
nestPackage("com.adobe.cq:core.wcm.components.all:2.8.0")
nestPackage("https://github.com/icfnext/aem-groovy-console/releases/download/14.0.0/aem-groovy-console-14.0.0.zip") // new one!
// ...                  
```

Resolving bundles and packages from urls while composing package

---

build.gradle.kts
docs/instance-plugin.md
docs/local-instance-plugin.md
docs/package-plugin.md
gradle.properties
src/functionalTest/kotlin/com/cognifide/gradle/aem/bundle/BundlePluginTest.kt
src/functionalTest/kotlin/com/cognifide/gradle/aem/instance/local/LocalInstancePluginTest.kt
src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt
src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildTest.kt
src/main/kotlin/com/cognifide/gradle/aem/bundle/BundlePlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/BackupManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/InstallResolver.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Condition.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/InstanceStep.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Provisioner.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Step.kt
src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageOptions.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/tasks/InstanceStatus.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/PackagePlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageCompose.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageValidate.kt

impl of #660 #542 ; @sabberworm 
when using `nestPackageProject` or `installBundleProject` building assembly package will also cause running unit tests for installed bundle and package validation for nested package.

Package validate task extracted

---

build.gradle.kts
docs/package-sync-plugin.md
gradle.properties
src/main/kotlin/com/cognifide/gradle/aem/common/file/ZipFile.kt
src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageOptions.kt
src/main/kotlin/com/cognifide/gradle/aem/common/pkg/PackageValidator.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/PackagePlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/PackageSyncPlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageConfig.kt

impl of #654 
imagine:
sh gradlew :app:aem:ui.apps:packageConfig -Ppackage.config.pid=org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet  
then GAP will retrieve OSGi config, serialize it and download and put it into app/aem/ui.apps/src/main/content/jcr_root/apps/example/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet.xml  
PID specified could have wildcards to sync multiple configs at once
motivation?
when saving OSGI configuration it is needed to rewrite properties from /system/console/configMgr/{pid} window displayed, then values need to be rewritten with type casts, comma delimited and escaped. Many things that we could do wrong. This new task eliminates many problems when transferring OSGi configuration to VCS.

Package config sync task

---

docs/bundle-plugin.md
docs/package-plugin.md
src/functionalTest/kotlin/com/cognifide/gradle/aem/bundle/BundlePluginTest.kt
src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt
src/main/kotlin/com/cognifide/gradle/aem/bundle/BundlePlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/common/CommonPlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/PackagePlugin.kt
src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/PackageCompose.kt

see discussion: #542 
@sabberworm almost done; see functional tests
todo only listing bundle dependencies in published pom.xml
edit: listing bundle dependencies not needed as of bundles should have only compileOnly dependencies; Gradle by default for regular jars is only listing implementation/api dependencies so nothing to change here.

Easy package and bundle Maven publication with Gradle metadata support

---

src/main/kotlin/com/cognifide/gradle/aem/common/instance/action/AwaitDownAction.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/action/AwaitUpAction.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/TimeoutCheck.kt

prevents waiting 10 min for same when instance has never responded yet
impl of #681

Unavailable timeout

---

src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/sync/Cleaner.kt

These attributes are added to Live Copy pages on every Rollout. We don't
want to keep them in the project repository after running `sync' task.

Remove cq:lastRolledout* attributes on sync

---

src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/TimeoutCheck.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/provision/Provisioner.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/ReplicationAgent.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/repository/Repository.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/status/Status.kt
src/main/kotlin/com/cognifide/gradle/aem/common/tasks/SyncFileTask.kt

see usage: https://github.com/Cognifide/aem-project-archetype/blob/master/src/main/archetype/build.gradle.kts#L118
```kotlin
aem {
instance {
provisioner { // https://github.com/Cognifide/gradle-aem-plugin/blob/master/docs/instance-plugin.md#task-instanceprovision
deleteReplicationAgents() // optionally :)
configureReplicationAgentAuthor("publish") { enable(publishInstance) }
configureReplicationAgentPublish("flush") { enable("http://localhost:80/dispatcher/invalidate.cache") }
deployPackage("com.neva.felix:search-webconsole-plugin:1.3.0")
}
}
}
```

Replication agents API + instance management improvements

---

src/main/kotlin/com/cognifide/gradle/aem/common/instance/ControlTrigger.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt

implementation of #758 
also improves a little bit UX because instead of seeing that all bundles are down when turning on instance... now it is visible "Starting instance" message which is more adequate 
also may be a fix for #647

Local instance up retry

---

src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceUrl.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/TimeoutCheck.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/check/UnavailableCheck.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/service/status/Status.kt

supplement for #814
after changing password e.g via:
`instance.default.password=xxx` to `instance.default.password=yyy`
and running `instanceRestart` AEMs will relaunch with a new admin password.
this improvement modifies a bit behavior of the task `instanceDown` so that it will work even without access to AEM through basic auth.

Soft instance down

---

src/main/kotlin/com/cognifide/gradle/aem/common/instance/IdType.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/Instance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/InstanceUrl.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt

also might improve #647 ; instead of parallel start.script execution, GAP will do it sequentially because seems that AEM does not like it :/

Instance HTTP url enumeration

---

src/main/kotlin/com/cognifide/gradle/aem/AemExtension.kt
src/main/kotlin/com/cognifide/gradle/aem/AemVersion.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstance.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/LocalInstanceManager.kt
src/main/kotlin/com/cognifide/gradle/aem/instance/LocalInstancePlugin.kt

if plugin `com.cognifife.aem.instance.local` is applied and Quickstart JAR set, then GAP will automatically assign to all projects applying `com.cognifide.aem.common` recent compatible version of Java to be used in:
*   launching AEM
*   compiling Java / making OSGi bundles
*   launching Maven in hybrid builds
As an effect, property
```
javaSupport.version=11 
```
will be no longer needed as GAP will automatically infer the best compatible Java version for AEM.

Java version inferring by AEM jar

---

src/main/kotlin/com/cognifide/gradle/aem/common/mvn/DependencyGraph.kt
src/main/kotlin/com/cognifide/gradle/aem/common/mvn/MvnBuild.kt

For more complex Maven modules structure, calculating dependencies between modules could be slow.
By introducing lookup cache, I reduced configuration phase time by about 8 seconds so that it behaves almost instant.

Maven build performance improvement

---

launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/BuildScaffolder.kt
launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/ForkScaffolder.kt
launcher/src/main/kotlin/com/cognifide/gradle/aem/launcher/MiscScaffolder.kt

I figured that GEP should be entirely removed from the launcher in order to get rid of dispatcher, for which it is not feasible to maintain compatibility with the new AEM Project Archetype released by Adobe.

Remove AEP from launcher

---

build.gradle.kts
src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/QuickstartResolver.kt

if sb will update sdk zip then GAP will erase previously unpacked SDK and unpack again AEM SDK JAR automatically.
`docker load` is run each time `envUp` task is called and during this task it is check docker-compose.yml file. if loaded image name and version changes then `envUp` task will destroy env and create it again so it should work as a whole.

SDK version updating

---

build.gradle.kts
gradle.properties
src/main/kotlin/com/cognifide/gradle/aem/common/asset/AssetManager.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/local/QuickstartResolver.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/InstanceAnalyzer.kt
src/main/kotlin/com/cognifide/gradle/aem/common/instance/tail/LogNotifier.kt
src/main/kotlin/com/cognifide/gradle/aem/common/mvn/MvnGav.kt

What about: 
```
> Task :generateMetadataFileForPluginMavenPublication
Execution optimizations have been disabled for task ':generateMetadataFileForPluginMavenPublication' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: 'C:\projects\gradle-aem-plugin\build\libs\aem-plugin-16.0.0-alpha4-javadoc.jar'. Reason: Task ':generateMetadataFileForPluginMavenPublication' uses this output of task ':publishPluginJavaDocsJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
- Gradle detected a problem …
```

#885 Deprecation fix
